### ISSUE TITLE
Changes did not trigger docs upload

### ISSUE THREAD

**Issue by ocefpaf** [sea-mat/sea-mat#11]
The change https://github.com/sea-mat/sea-mat/commit/6ffb6825274d849a5b925fed01812c9288b26abc from #10 did not make into the pages.

Travis-CI reports that there is no change in the docs, see https://travis-ci.org/sea-mat/sea-mat#L340, but that is clearly wrong.

Not sure if we are doing something wrong or if `doctr` is not comparing against the right doc page.

cc @asmeurer

**Comment by asmeurer** [comment]
Ah crap, this is my fault. I omitted the `git rm -rf .` when I told you how to create `gh-pages`, but apparently that's quite important (doctr itself [does it](https://github.com/drdoctr/doctr/blob/4883ca3c49472890255e5707b2aaf45eaef1b6c9/doctr/travis.py#L233) but I left it out for some reason). What happened is that it you committed all the uncommitted files to `gh-pages` when you created it, including `_site`. So when doctr runs a `git checkout gh-pages`, it clears the ignored `_site` with the `gh-pages` `_site`, which is committed as it was when you created the branch (I would have thought git would error here, but I guess not).

So you need to run 

```
git checkout gh-pages
git rm -rf .
git commit -a -m "Clear gh-pages"
git push origin gh-pages
```

Then trigger a new Travis build, to rebuild the docs from scratch. 

Sorry for the issue. The good news is that we've fixed the issue with [creating gh-pages automatically](https://github.com/drdoctr/doctr/pull/150) in doctr, so the manual steps you did shouldn't be necessary anymore.

**Comment by ocefpaf** [comment]
Thanks @asmeurer. The `rm -f` makes sense. I am so used to force push `subtrees` that I ignored how `doctr` makes the comparison to commit only the changes.

And thanks for the bug fix. I will be using that in another project soon.

@rsignell-usgs When re-starting Travis-CI we hit a problem with `mkdocs`, but I believe that one will be easy to fix.

**Comment by asmeurer** [comment]
If you add `set -e` to your `.travis.yml` it will prevent doctr from running when the docs build fails (see https://drdoctr.github.io/doctr/).

**Comment by ocefpaf** [comment]
Doing that now. Thanks.
